# Generated by Django 5.2.8 on 2025-11-24 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_remove_admissionresult_applicant_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionresult',
            name='english_percentile',
        ),
        migrations.RemoveField(
            model_name='admissionresult',
            name='total_average_grade',
        ),
    ]
